language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
before_install:
  - "cpanm -n Dist::Zilla"
install:
  - "dzil authordeps | xargs cpanm"
  - "dzil listdeps | xargs cpanm"
  - "cpanm -n Pod::Weaver::Section::Changes"
  - "cpanm -n Pod::Elemental::Transformer::List"
script: "dzil test --release --author"
