language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
before_install:
  - "cpanm -n Dist::Zilla"
  - "cpanm -n Dist::Zilla::Plugin::AutoPrereqs"
  - "cpanm -n Dist::Zilla::Plugin::CheckChangeLog"
  - "cpanm -n Dist::Zilla::Plugin::EOLTests"
  - "cpanm -n Dist::Zilla::Plugin::Git::Check"
  - "cpanm -n Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch"
  - "cpanm -n Dist::Zilla::Plugin::Git::Commit"
  - "cpanm -n Dist::Zilla::Plugin::Git::Tag"
  - "cpanm -n Dist::Zilla::Plugin::NextRelease"
  - "cpanm -n Dist::Zilla::Plugin::OurPkgVersion"
  - "cpanm -n Dist::Zilla::Plugin::PodCoverageTests"
  - "cpanm -n Dist::Zilla::Plugin::PodSyntaxTests"
  - "cpanm -n Dist::Zilla::Plugin::PodWeaver"
  - "cpanm -n Dist::Zilla::Plugin::Prereqs"
  - "cpanm -n Dist::Zilla::Plugin::PruneFiles"
  - "cpanm -n Dist::Zilla::Plugin::Test::NoTabs"
  - "cpanm -n Dist::Zilla::Plugin::Test::Perl::Critic"
  - "cpanm -n Dist::Zilla::Plugin::Test::PodSpelling"
  - "cpanm -n Dist::Zilla::PluginBundle::Basic"
  - "cpanm -n Dist::Zilla::PluginBundle::Filter"
install: "dzil listdeps | xargs cpanm"
script: "dzil test --release --author"
