language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
before_install:
  - "cpanm -n Dist::Zilla"
install:
  - "sudo apt-get update"
  - "sudo apt-get install aspell aspell-en"
  - "dzil authordeps | xargs cpanm -n"
  - "dzil listdeps | xargs cpanm -n"
  - "cpanm -n Pod::Weaver::Section::Changes"
  - "cpanm -n Pod::Elemental::Transformer::List"
  - "cpanm -n Test::Perl::Critic"
  - "cpanm -n Pod::Coverage::TrustPod"
  - "cpanm -n Archive::Extract"
  - "cpanm -n Hash::AsObject"
  - "cpanm -n Log::Log4perl"
  - "cpanm -n Template"
  - "cpanm -n Types::Standard"
  - "cpanm -n DateTime::Format::DateManip"
script: "dzil smoke --release --author"
