language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
before_install:
  - "cpanm -n Dist::Zilla"
install:
  - "sudo apt-get update"
  - "sudo apt-get install aspell aspell-en"
  - "dzil authordeps | xargs cpanm"
  - "dzil listdeps | xargs cpanm"
  - "cpanm -n Pod::Weaver::Section::Changes"
  - "cpanm -n Pod::Elemental::Transformer::List"
  - "cpanm -n Test::Perl::Critic"
  - "cpanm -n Pod::Coverage::TrustPod"
script: "dzil test --release --author"
