dir:
  repository: ospkg/distfiles
  configs: ospkg/configs
  work: ospkg/work
  fakeroot: ospkg/fakeroot
perms:
  user: root
  group: root
plugins:
  solaris:
    "2.10": "OS::Package::Plugin::Solaris::SVR4"
