dir:
  base: ~/.ospkg
  repository: ~/.ospkg/distfiles
  configs: ~/.ospkg/configs
  work: ~/.ospkg/work
  fakeroot: ~/.ospkg/fakeroot
  packages: ~/.ospkg/packages
package:
  user: root
  group: root
  category: application
plugin:
  solaris:
    "5.10": "OS::Package::Plugin::Solaris::SVR4"
